### ISSUE TITLE
Mention that `project: write` must be enabled for API key in README

### ISSUE THREAD

**Issue by rhys-vdw** [40thieves/webpack-sentry-plugin#14]
Or perhaps link to [this section](https://docs.sentry.io/clients/javascript/sourcemaps/#uploading-source-maps-to-sentry)

Took a bit of poking around to work out which of the permissions were required. I imagine this could make things easier for people.

**Comment by 40thieves** [comment]
That's a good point 👍. I'll try to find some time to add that tonight

**Comment by 40thieves** [comment]
Closed with ce3ba61bb0268b82a8124fdf5edcaab3b263c9bc

**Comment by rhys-vdw** [comment]
Nice one, cheers. Plugin is working a treat btw, thanks.
