### ISSUE TITLE
release hash sharing

### ISSUE THREAD

**Issue by jaredleechn** [40thieves/webpack-sentry-plugin#16]
If front end wants to report via sentry, it should get config of release hash, but the hash generated by compilation.hash based on front end source code

The git commit id may be not a good choice for difference between multi build in diff machines for the updating of dependencies

So is there any prictices or ideas to sharing hash code between source code and this plugin

very thanks 😃

**Comment by 40thieves** [comment]
Hi!

I just want to check my understanding of your question: You can't use the webpack compilation hash? Because it is provided as an argument if you pass a function to the `release` option. So you can do:

```js
var config = {
  plugins: [
    new SentryPlugin({
      release: function(hash) {
        return hash
      }
    })
  ]
}
```

You also can't use the git commit hash? The plugin can't really help you there as it depends on your build set up.

If those aren't viable, maybe you could generate one based on a timestamp? Would something like this help: https://gist.github.com/kitek/1579117? I'm afraid I don't know what would be considered best practice here 😞

**Comment by jaredleechn** [comment]
Thanks for the reply

The question is how to report the event to sentry with the same hash rather than getting compilation.hash in the release function arguments. The sharing I meant is between the follow twos:
```
Raven.config('dsn', { release: theHash });  // source code
webpackConfig.plugins.push(new Sentry({ release: hash => theHash }));  // webpack config
```

`theHas` need to be same for tracing event with source-map in sentry, so I think the twos should be generated the same time

**Comment by 40thieves** [comment]
Ah, I think I see what you mean.

I've done this 2 ways in the past. The simplest method is to build as part of a continuous release pipeline. Currently at my work we use Heroku and [this buildpack](https://github.com/febeling/webpack-rails-buildpack).

But without this pipeline it is a bit trickier. I have done a "manual" release previously, where I copy/pasted the release hash into a environment variable. This environment variable is then injected when the build is served by our application server. A kind-of similar process is inlining a manifest file, for which there is a (short) section in the webpack docs: https://webpack.js.org/guides/caching/#manifest-inlining

> Git hash maybe not a good idea, for building in different machine, the results are different. In others words, the result generated by a same commit hash maybe be different for dependencies updating

I've always use the latest commit hash, which should always be the same, unless you're committing your dependencies?

Hope that helps!

**Comment by jaredleechn** [comment]
Thank, it really helps!

Although the git hash for me is not stable for depending on many modules in [semver version](http://semver.org/), but it can solve most problems

Another question, will u support update the release when same release hash occurs?

```
try {
  createHash()
  uploadFile()
} catch (e) {
  updateReleaseOrUploadFileOnly()
}
```

**Comment by 40thieves** [comment]
> Another question, will u support update the release when same release hash occurs?

Ah, that's a good point. Hadn't thought of that. Created https://github.com/40thieves/webpack-sentry-plugin/issues/17 to track that
