### ISSUE TITLE
Handle already existing release hash

### ISSUE THREAD

**Issue by 40thieves** [40thieves/webpack-sentry-plugin#17]
As discussed in https://github.com/40thieves/webpack-sentry-plugin/issues/16#issuecomment-289450544, currently creation of releases will crash if the release hash stays the same.

Potential options:

1. Crash with better error message
2. Overwrite the existing release's files (how does Sentry api handle this?)
3. Delete the existing release and try again

**Comment by nfm** [comment]
We just ran into this after a failed deploy. It looks like the Sentry API returns a `409 - Conflict` status code when this happens. I'm not sure what the best thing to do is here, but an option to ignore this type of error (and not others) would solve our issue. The current `suppressErrors` option swallows this error, and others that we would want to raise on.

**Comment by langfors** [comment]
Similarly, we have a use case where we would like to tie multiple development builds to a specific development 'release' and use this 'release' to bundle sentry caught exceptions.  This is difficult when we can't harmlessly register the same 'release'.  +1 for an ignore duplicate release error flag.
