### ISSUE TITLE
Specify all required permissions for api token in documentation

### ISSUE THREAD

**Issue by justin-hackin** [40thieves/webpack-sentry-plugin#18]
Documentation specifies:

`
apiKey: Sentry api key (Generate one here, ensure that project:write is selected under scopes)
`

However, when I create a token with only specified scope, I get permissions errors.  Then I created a token with the default scopes plus the project:write added and I don't get the permission errors anymore.

**Comment by 40thieves** [comment]
Whoops, that's a great point. I just blindly copied from Sentry's API docs. I need to test, but I believe the required scopes are `project:read`, `project:write` & `project:releases`.

I'll check those & add to the docs when I get some time

**Comment by 40thieves** [comment]
Fixed with d65c9d4040ec991058e65f107f1f4c5b59413dd8
