### ISSUE TITLE
Change "organisation" spelling from BE to AE

### ISSUE THREAD

**Issue by amannn** [40thieves/webpack-sentry-plugin#21]
Thanks for this plugin, it's really helpful!

I've noticed that the `organisation` option is spelled in British English, whereas Sentry [uses](https://docs.sentry.io/api/organizations/post-organization-index/) the American English version (`organization`).

To avoid confusing errors, it could be helpful to switch to the AE spelling or at least accept it as an alias. What do you think?

**Comment by chrisnicola** [comment]
It would make sense to not have this be inconsistent with Sentries own naming conventions.
