### ISSUE TITLE
Update documentation request

### ISSUE THREAD

**Issue by NiltiakSivad** [40thieves/webpack-sentry-plugin#22]
I got tripped up three times getting this setup on premise:

1. According to the Sentry documentation:

```
organisation: Required, Sentry organisation to upload files to
project: Required, Sentry project to upload files to
```

I was continually getting 401s, I didn't realize these were supposed to be the slugs, until reading through the code. Would be helpful to mention that fact.

2. Mentioning the `apiKey` is the same as the new Auth Tokens would be nice, since API Keys were previously a completely different thing in Sentry.

3. `baseSentryURL` needs to have the suffix `/api/0/projects`

**Comment by ismay** [comment]
I've run into the first problem as well. The returned error is quite non-descriptive, and from the documentation it isn't immediately obvious that the 'short name' (as sentry calls it in their ui) needs to be used.
