### ISSUE TITLE
How do I use the webpack build hash outside of the callback?

### ISSUE THREAD

**Issue by Birowsky** [40thieves/webpack-sentry-plugin#23]
I obviously need to send it to Raven as a config param, but I'm not sure how to go about it. Do you guys have a recommended way?

Ideally I'd be able to somehow access the hash in the context of the DefinePlugin since that's where I'm passing env values to the js app.

**Comment by brandonmp** [comment]
[this might help](https://github.com/webpack/docs/wiki/list-of-plugins#extendedapiplugin):

```
```
new webpack.ExtendedAPIPlugin()
```
Adds useful free vars to the bundle.

`__webpack_hash__`  The hash of the compilation available as free var.
```


Personally I use the `git hash`. idk if this works for everyone's workflow, but I have a `sh` script I run on deploys that just inserts the current `git hash` into the `.env` file in my project root, like so:

```
sed -Ei "s/(REPO_GIT_HASH=).*/\1$(git rev-parse HEAD)/g" ./.env
```

**Comment by dimitarnestorov** [comment]
DefinePlugin is what we use in our team
