### ISSUE TITLE
switch from api key to auth header

### ISSUE THREAD

**Issue by brandonmp** [40thieves/webpack-sentry-plugin#28]
Looks like api keys are deprecated for the purposes of releases:

> Once added, Sentry will automatically collect commits for the repository, and you can begin referencing it in releases. To do so, you’ll need to send refs along when you create a release. Note: You need to make sure you’re using Auth Tokens not API Keys, which are deprecated. - [source](https://docs.sentry.io/learn/releases/#releases-are-better-with-commits)

I don't know the API very well, so I'm not sure if they're only deprecated for the purposes of logging commits, but I just stumbled onto this in the docs so wanted to leave a note here.

**Comment by schneidmaster** [comment]
I think this is really just a documentation update. I am already passing an auth token to the `apiKey` parameter for this plugin and everything works fine.
