### ISSUE TITLE
Call for collaborators

### ISSUE THREAD

**Issue by 40thieves** [40thieves/webpack-sentry-plugin#34]
I've become quite burned out on this project (and other OSS projects). It would be great if there were some volunteers for collaborators. Please reply to this thread if you'd like to volunteer. 

(Disclaimer: I've actually never had collaborators so I don't actually know what I'm doing. Help in these regards would be nice 🙂)

**Comment by schneidmaster** [comment]
Oh hey, I just commented in #25 and offered to help out. 🙂 

I also maintain [sitemap-webpack-plugin](https://github.com/schneidmaster/sitemap-webpack-plugin) (which I wrote) and help maintain [asset-map-webpack-plugin](https://github.com/mtscout6-team/asset-map-webpack-plugin). For the latter, the original author just gave me write permissions on the repo and added me as an npm contributor so I could publish new releases.

**Comment by rhys-vdw** [comment]
Heya, I'd be interested in collaboration as I mentioned [here](https://github.com/40thieves/webpack-sentry-plugin/pull/27#issuecomment-326499888). Mainly so that I have the option of addressing issues that arise for us downstream.

No stranger to maintaining open source npm projects. :)

**Comment by 40thieves** [comment]
Thanks so much!

Added @schneidmaster as collaborator on GH & npm. And added @rhys-vdw as collaborator on Github - it wasn't immediately obvious what your npm user name was, so if you want to be added there too could you send that along.

Closing.

**Comment by rhys-vdw** [comment]
Cheers @40thieves. My npm profile is [here](https://www.npmjs.com/~rhys-vdw).

**Comment by 40thieves** [comment]
Sorry it's taken me so long to get around to this, but now added you as a npm collaborator @rhys-vdw

**Comment by rhys-vdw** [comment]
Cheers
