### ISSUE TITLE
Release commits are untagged

### ISSUE THREAD

**Issue by rhys-vdw** [40thieves/webpack-sentry-plugin#44]
We're missing tags for 1.12.0 and 1.13.0

**Comment by schneidmaster** [comment]
Good find, I didn't realize [GitHub tags](https://github.com/40thieves/webpack-sentry-plugin/tags) didn't also create "real" git tags (still a bit confused about why that's not the default behavior). Tagged the relative commits and pushed.

**Comment by rhys-vdw** [comment]
They're still not in the dropdown:

![image](https://user-images.githubusercontent.com/822105/30146514-da91908c-93db-11e7-83b7-23cb30922b1a.png)

Make sure you include the `--tags` flag:

```
git push --tags
```

**Comment by schneidmaster** [comment]
Hmm, I'm confused. They're definitely pushed up. I see `1.12.0` and `1.13.0` in the dropdown, just not `v1.12.0` and `v1.13.0`.

<img width="1144" alt="screenshot 2017-09-07 00 54 34" src="https://user-images.githubusercontent.com/1896112/30146634-27d4d478-9367-11e7-8e72-72e4c2e1c453.png">

**Comment by schneidmaster** [comment]
Oh, I'm dumb. The `origin` git remote is my fork and I have this repo set to `upstream`. Pushed now.

**Comment by schneidmaster** [comment]
I think GitHub creates tags in the dropdown that match its releases (like `1.12.0` and `1.13.0`) but the tags with `v` in front were either created manually for each release or came from some CLI that 40thieves used to publish.

**Comment by rhys-vdw** [comment]
Ah, I've no idea. In my other project I supply the versions as tags without the `v` prefix manually and then GitHub populates the releases tab from those (I think).
