### ISSUE TITLE
Plugin receiving 404 

### ISSUE THREAD

**Issue by joeyfigaro** [40thieves/webpack-sentry-plugin#46]
```ERROR in Sentry Plugin: StatusCodeError: 404 - "{\"detail\": \"\"}"```

Have tried auth tokens with limited scope and full permissions. Leaving this here for now, can investigate further this afternoon.

**Comment by schneidmaster** [comment]
You should check to ensure you're providing the correct organization name (the "short name" under Organization Settings in Sentry). Providing your full organization name and/or any typos there would cause a 404.

**Comment by joeyfigaro** [comment]
@schneidmaster Thanks for the quick response, bud. Trying that out.

**Comment by joeyfigaro** [comment]
@schneidmaster That did it. 💯 💯
