### ISSUE TITLE
413 Entity Too Large

### ISSUE THREAD

**Issue by kjanoudi** [40thieves/webpack-sentry-plugin#50]
Referring to: https://docs.sentry.io/clients/javascript/sourcemaps/#uploading-source-maps-to-sentry

indicates that we should be able to upload up to 40mb. Currently, i am getting a 413 error when uploading more than 20mb. I have narrowed the issue down to this:

When using https://docs.sentry.io/api/releases/post-organization-release-files/ , the request limit seems to be lower than when using https://docs.sentry.io/api/releases/post-project-release-files/ (which is what the initial link at the top of this post seems to use). I believe this is a recent issue as a result of https://github.com/40thieves/webpack-sentry-plugin/pull/36

**Comment by kjanoudi** [comment]
Note that version 1.11.0 of this plugin is working correctly.

**Comment by schneidmaster** [comment]
@kjanoudi Thanks for the report. Using the organization release endpoint was necessary for the plugin to support Sentry's release commits. You might consider opening a support ticket with Sentry to ask whether they intended for the endpoints to have different max upload sizes; that seems like a strange behavior to me. Otherwise I would be amenable to having a configuration option for which endpoint ought to be used.

**Comment by drewlustro** [comment]
Related / Unrelated Q: Does Sentry have an API-wide max Entity size? (for artifacts or incident reports)

Is there a way to increase it on the dashboard?

**Comment by schneidmaster** [comment]
@drewlustro I'm not sure. Note that this is an unofficial community project, I/we don't have any formal affiliation with Sentry. I'd recommend writing into their support with your questions.

**Comment by schneidmaster** [comment]
@kjanoudi Closing the issue as from https://github.com/getsentry/sentry/issues/6331 it sounds like this was a misconfiguration on sentry.io that's been resolved.

**Comment by drewlustro** [comment]
@schneidmaster - my man, thanks for the info.

Love the plugin, thanks for authoring; using it in production at @capsulehealth FWIW

**Comment by schneidmaster** [comment]
@drewlustro Thanks! Most of the authorship credit goes to @40thieves though, I just help maintain the plugin these days.

**Comment by 40thieves** [comment]
No all credit to @schneidmaster (& @rhys-vdw) for maintaining :)
