### ISSUE TITLE
409 Errors

### ISSUE THREAD

**Issue by kjanoudi** [40thieves/webpack-sentry-plugin#51]
When setting the CI flag to true, webpack treats warnings as errors. So even if we set `suppressConflictError` to true, it still reports a warning, which is then treated as an error. I see a couple options: 

1) allow a "overwriteExistingArtifcats" flag, or similar
2) Do not warn or error on the conflict error if the `suppressConflictError` flag is set to true

Any thoughts?

**Comment by rhys-vdw** [comment]
> which is then treated as an error

Interesting. Is this perhaps a configurable setting in WebPack. It seems like the correct behaviour for `webpack-sentry-plugin`.

**Comment by rhys-vdw** [comment]
> allow a "overwriteExistingArtifcats" flag, or similar

This shouldn't be necessary. If the version is your current git hash, then the existing artifacts should be exactly the same as the ones that were rejected.

**Comment by kjanoudi** [comment]
Okay, I'll close this for now and try to configure the create-react-app project I'm using. Thanks

**Comment by rhys-vdw** [comment]
Check out facebookincubator/create-react-app#1150

**Comment by Grsmto** [comment]
@kjanoudi did you find a solution for this? Even using Webpack `stats: 'none'` I'm still getting that warning that breaks my CI :/

**Comment by kjanoudi** [comment]
i removed this from my `scripts/build.js` 

```
if (
        process.env.CI &&
        (typeof process.env.CI !== 'string' ||
          process.env.CI.toLowerCase() !== 'false') &&
        messages.warnings.length
      ) {
        console.log(
          chalk.yellow(
            '\nTreating warnings as errors because process.env.CI = true.\n' +
              'Most CI servers set it automatically.\n'
          )
        );
        return reject(new Error(messages.warnings.join('\n\n')));
      }
```

**Comment by kjanoudi** [comment]
@Grsmto
