### ISSUE TITLE
ERROR in Sentry Plugin: RequestError: Error: connect ECONNRESET 192.168.1.193:9005

### ISSUE THREAD

**Issue by DeepenLau** [40thieves/webpack-sentry-plugin#53]
This is a weird issue
After deploy the sentry server at my own server, i use webpack-sentry-plugin to upload my project's sourcemap file. 
Sometimes, i get the error message that shows me ERROR in Sentry Plugin: RequestError: Error: connect ECONNRESET 192.168.1.193:9005,
![image](https://user-images.githubusercontent.com/14030995/32442012-c73804a2-c334-11e7-98e0-6325ee364488.png)

 but i checkout the releases , it shows me that my files was uploaded succussfully, but still show me the error message
![image](https://user-images.githubusercontent.com/14030995/32441970-98131144-c334-11e7-9c46-8b987922fd36.png)
i don't know how to figure it out
Thanks!

**Comment by schneidmaster** [comment]
Hey there. Generally speaking, ECONNRESET in Node means that the remote server (i.e. your Sentry server) unexpectedly closed the TCP connection before it was finished. This could be for any number of reasons that would all be related to your specific setup -- i.e. maybe your Sentry install is misconfigured somehow, maybe it's behind nginx/apache with a max request size that's being reached, maybe something with the firewall, maybe intermittent network problems between you and your server, etc etc. I don't think it's an issue we'll be able to help you with as the plugin is functioning correctly.

**Comment by DeepenLau** [comment]
Thanks you so much!
I will try to figure it out.
