### ISSUE TITLE
400 Invalid project slugs

### ISSUE THREAD

**Issue by benoj** [40thieves/webpack-sentry-plugin#56]
Hi,

I am using the following project configuration:

```
  new SentryPlugin({
    organization: '<SHORT_NAME>',
    project: '<PROJECT>,
    apiKey: '<API_KEY>',
    release: (hash) => hash
  })
```

However I am getting the following error:

`ERROR in Sentry Plugin: StatusCodeError: 400 - "{\"projects\": [\"Invalid project slugs\"]}"`

**Comment by schneidmaster** [comment]
Hi - that error is directly from Sentry, and means that whatever you've provided for the project key does not match the slug of one of your Sentry projects.

**Comment by benoj** [comment]
my project name has `.` in the title which were ignored for the slug!

My bad! thanks
