### ISSUE TITLE
support webpack4

### ISSUE THREAD

**Issue by xutm** [40thieves/webpack-sentry-plugin#57]
When I upgrade webpack4 from webpack3, have a problem 
`
ERROR in Sentry Plugin: RequestError: Error: getaddrinfo ENOTFOUND fse.int.xiaohongshu.com fse.int.xiaohongshu.com:80
`

**Comment by schneidmaster** [comment]
That error indicates that your domain is incorrect (not publicly resolvable, etc). There shouldn't be anything from webpack 3 -> webpack 4 that affects this. Other folks have reported in #59 that the plugin works fine with webpack 4 (I just haven't gotten around to reviewing that PR to formally support it).

**Comment by rhys-vdw** [comment]
Can confirm that we have no issues with webpack 4.
