### ISSUE TITLE
Source code not found for webpack:///....

### ISSUE THREAD

**Issue by Cherry** [40thieves/webpack-sentry-plugin#61]
Firstly, thanks for this awesome plugin. It's been working great for us in production for some months!

I'm not sure if something on Sentry's end changed recently, but we're no longer seeing our code in Sentry from the uploaded sourcemaps. 
```
Source code was not found for webpack:///../node_modules/angular/angular.js
Source code was not found for webpack:///../node_modules/@uirouter/angularjs/release/stateEvents.min.js
Source code was not found for webpack:///./apps/instances/modules/pixark/app.js
```
is what Sentry is reporting on any issues reported from our website, for example.

Our filenameTransform function is as follows:
```javascript
filenameTransform: function(filename){
	return '~/assets/' + filename;
},
```

Again, this has been working just fine for months so I imagine something on Sentry's end changed? Would changing our `filenameTransform` function to be prefixed with `webpack://` perhaps work?

**Comment by schneidmaster** [comment]
Hey, sorry you never got a response on this. I've had to play around with the `filenameTransform` to get the sourcemaps linked up correctly; it depends on your webpack output path configuration. Also I'm not sure if those library files would have sourcemaps in the first place.
