### ISSUE TITLE
ERROR in Sentry Plugin: StatusCodeError: 403

### ISSUE THREAD

**Issue by dingshiwei** [40thieves/webpack-sentry-plugin#63]
when I exec npm run build command, i get this error, I'm sure my token and project_name and organization are right, anyone has this error?
![image](https://user-images.githubusercontent.com/12472771/41287685-24b875e8-6e76-11e8-8ab7-f1eaeb55aa82.png)

**Comment by schneidmaster** [comment]
Hi there! Can you confirm that your auth token has the `project:releases` scope enabled? That would definitely cause this error if not.

**Comment by Jsonya** [comment]
@schneidmaster  I also get a similar error for this, but the statusCode is 401 and the detail is Invalid token. I don't know why , I'm confirm my token is right.

**Comment by LFmadongsheng** [comment]
> 当我执行npm run build命令时，我收到此错误，我确定我的令牌和project_name和组织是正确的，任何人都有此错误？
> ![图片](https://user-images.githubusercontent.com/12472771/41287685-24b875e8-6e76-11e8-8ab7-f1eaeb55aa82.png)

borther,are you resolved this question?

**Comment by Moirafu** [comment]
i have same problem，have you got any idea how can i fix it?

**Comment by dingshiwei** [comment]
> i have same problem，have you got any idea how can i fix it?

sorry, i have to use another plugin.

**Comment by mqklin** [comment]
@dingshiwei which one?

**Comment by ashen9** [comment]
i have same problem，have you got any idea?

**Comment by schneidmaster** [comment]
This error is coming directly from Sentry -- it thinks your auth token is not authorized to perform one of the actions it's taking (creating a release and uploading artifacts to it). It's hard for us to debug on this end because it's likely specific to your Sentry configuration.

**Comment by schneidmaster** [comment]
Closing this issue, let me know if you're able to identify an issue specific to this plugin

**Comment by lishichao1002** [comment]
same question。
 change `baseSentryURL: 'https://xxx.com'`  to `baseSentryURL: 'https://xxx.com/api/0'`
