### ISSUE TITLE
connect ETIMEDOUT 35.188.42.15:443

### ISSUE THREAD

**Issue by yiqianglin** [40thieves/webpack-sentry-plugin#64]
![image](https://user-images.githubusercontent.com/15794229/41340592-520587b6-6f2a-11e8-9b99-75ba5541cc26.png)
![image](https://user-images.githubusercontent.com/15794229/41340648-710e7b40-6f2a-11e8-941b-d56618b478e6.png)

**Comment by audiolion** [comment]
+1 I am getting the same error

**Comment by audiolion** [comment]
I think this is nothing to do with this library thought, sentry api just unavailable

**Comment by schneidmaster** [comment]
Yeah, this error message just means that the the Sentry API was unavailable for some reason. You might not be connected to the internet (or have local network problems), you might be behind a firewall, Sentry could be down (though I don't see any recent outages on their status page), etc. I don't think there's anything for us to do here.
