### ISSUE TITLE
Request: option to no-op when source map uploads fail

### ISSUE THREAD

**Issue by finnigantime** [40thieves/webpack-sentry-plugin#75]
When source map upload fails, we would like to log an error but continue with the webpack build and our CI release.

We use CircleCI as our CI pipeline. An engineer merged a branch to master and the deploy leg failed initially with this error: `ERROR in Sentry Plugin: RequestError: Error: Client network socket disconnected before secure TLS connection was established`.

Subsequently, when rerunning the failed deploy leg, we get this error: `ERROR in Sentry Plugin: StatusCodeError: 409 - "{\"detail\": \"A file matching this name already exists for the given release\"}"`

So, we cannot deploy this build anymore. We need to submit a new one with a dummy commit to get a deploy out. Instead, we'd prefer if we could rerun the initial build and have it succeed.

The fix here could take several forms:
- log but do not fail on all upload source map errors
- log but do not fail on failure to upload source maps specifically due to "file matching this name already exists"
- add an overwrite option to overwrite existing files with the same name
etc.

**Comment by schneidmaster** [comment]
Hi there! Options #1 and #2 are already possible. You can suppress all errors by setting the `suppressErrors` option to `true`, or you can suppress just the "file already exists" error by setting the `suppressConflictError` option to `true`.

**Comment by finnigantime** [comment]
awesome, ty!
