### ISSUE TITLE
ERROR in Sentry Plugin: StatusCodeError: 502

### ISSUE THREAD

**Issue by alexeychikk** [40thieves/webpack-sentry-plugin#88]
I build my project with Netlify and sometimes (not always) build fails with the following error: 
```
4:22:10 PM: ERROR in Sentry Plugin: StatusCodeError: 502 - "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.15.8</center>\r\n</body>\r\n</html>\r\n"
```

**Comment by schneidmaster** [comment]
This generally means that Sentry returned a 502 error when the plugin made a request to create a release/upload sourcemaps. You might try contacting their support when this happens, or checking their [status page](https://status.sentry.io). Or if you're using self-hosted Sentry, check that your instance is not down for some reason. I don't think the plugin can do much about this.

**Comment by alexeychikk** [comment]
I switched to @sentry/webpack-plugin. It always uploads files without 502 error.
