### ISSUE TITLE
Webpack 5 compatibility

### ISSUE THREAD

**Issue by MayaWolf** [40thieves/webpack-sentry-plugin#92]
Hi!

First off, thank you for this plugin - it is much easier, more convenient and more flexible to use than the official Sentry plugin.

Unfortunately, it doesn't seem to work with Webpack 5 due to [this issue](https://github.com/webpack/webpack/issues/8883). Would it be possible to provide a fix?

Thank you!

**Comment by schneidmaster** [comment]
Hi! I am happy to accept a PR implementing that change. Otherwise I will try to look into it myself when I get time, but it is not a super urgent priority for me since webpack 5 is still in beta with no release date announced as far as I know.
